package View;







/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Usuario
 */
public class JTelaEditarAluno extends javax.swing.JFrame {

    /**
     * Creates new form EditarAluno
     */
    public JTelaEditarAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelSenhaAL = new javax.swing.JLabel();
        buttonCancelar = new javax.swing.JButton();
        campoEmailAL = new javax.swing.JTextField();
        labelEmailAL = new javax.swing.JLabel();
        labelConfirmacaoSenhaAL = new javax.swing.JLabel();
        labelEnderecoAL = new javax.swing.JLabel();
        campoEnderecoAL = new javax.swing.JTextField();
        labelCEPAL = new javax.swing.JLabel();
        campoCEPAL = new javax.swing.JTextField();
        labelRGAL = new javax.swing.JLabel();
        campoRGAL = new javax.swing.JTextField();
        campoCPFAL = new javax.swing.JTextField();
        labelCPFAL = new javax.swing.JLabel();
        labelNomeAL = new javax.swing.JLabel();
        campoNomeAL = new javax.swing.JTextField();
        campoDataNascAL = new javax.swing.JTextField();
        labelEditAluno = new javax.swing.JLabel();
        buttonSalvar = new javax.swing.JButton();
        labelDataNascAL = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        labelSenhaAL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSenhaAL.setText("Senha:");
        jPanel1.add(labelSenhaAL);
        labelSenhaAL.setBounds(170, 340, 50, 17);

        buttonCancelar.setBackground(new java.awt.Color(255, 0, 0));
        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCancelar);
        buttonCancelar.setBounds(440, 470, 133, 23);

        campoEmailAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEmailALActionPerformed(evt);
            }
        });
        jPanel1.add(campoEmailAL);
        campoEmailAL.setBounds(170, 280, 250, 33);

        labelEmailAL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelEmailAL.setText("Email:");
        jPanel1.add(labelEmailAL);
        labelEmailAL.setBounds(170, 260, 41, 17);

        labelConfirmacaoSenhaAL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelConfirmacaoSenhaAL.setText("Confirmação de Senha:");
        jPanel1.add(labelConfirmacaoSenhaAL);
        labelConfirmacaoSenhaAL.setBounds(410, 340, 170, 17);

        labelEnderecoAL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelEnderecoAL.setText("Endereço:");
        jPanel1.add(labelEnderecoAL);
        labelEnderecoAL.setBounds(170, 200, 90, 17);

        campoEnderecoAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEnderecoALActionPerformed(evt);
            }
        });
        jPanel1.add(campoEnderecoAL);
        campoEnderecoAL.setBounds(170, 220, 290, 33);

        labelCEPAL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCEPAL.setText("CEP:");
        jPanel1.add(labelCEPAL);
        labelCEPAL.setBounds(480, 200, 120, 17);

        campoCEPAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCEPALActionPerformed(evt);
            }
        });
        jPanel1.add(campoCEPAL);
        campoCEPAL.setBounds(480, 220, 120, 33);

        labelRGAL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelRGAL.setText("RG:");
        jPanel1.add(labelRGAL);
        labelRGAL.setBounds(170, 140, 140, 17);

        campoRGAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRGALActionPerformed(evt);
            }
        });
        jPanel1.add(campoRGAL);
        campoRGAL.setBounds(170, 160, 200, 33);

        campoCPFAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCPFALActionPerformed(evt);
            }
        });
        jPanel1.add(campoCPFAL);
        campoCPFAL.setBounds(400, 160, 200, 33);

        labelCPFAL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCPFAL.setText("CPF:");
        jPanel1.add(labelCPFAL);
        labelCPFAL.setBounds(400, 140, 150, 17);

        labelNomeAL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNomeAL.setText("Nome:");
        jPanel1.add(labelNomeAL);
        labelNomeAL.setBounds(170, 80, 140, 17);

        campoNomeAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeALActionPerformed(evt);
            }
        });
        jPanel1.add(campoNomeAL);
        campoNomeAL.setBounds(170, 100, 200, 33);

        campoDataNascAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataNascALActionPerformed(evt);
            }
        });
        jPanel1.add(campoDataNascAL);
        campoDataNascAL.setBounds(400, 100, 200, 33);

        labelEditAluno.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelEditAluno.setText("Editar Aluno");
        jPanel1.add(labelEditAluno);
        labelEditAluno.setBounds(120, 20, 220, 40);

        buttonSalvar.setBackground(new java.awt.Color(0, 255, 0));
        buttonSalvar.setText("Salvar");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSalvar);
        buttonSalvar.setBounds(580, 470, 133, 23);

        labelDataNascAL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelDataNascAL.setText("Data de nascimento:");
        jPanel1.add(labelDataNascAL);
        labelDataNascAL.setBounds(400, 80, 150, 17);

        jPasswordField1.setText("jPasswordField1");
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(410, 370, 140, 20);

        jPasswordField2.setText("jPasswordField1");
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(170, 370, 120, 20);

        jPanel2.setBackground(new java.awt.Color(0, 255, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(694, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SoFiT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(738, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void campoEmailALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmailALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEmailALActionPerformed

    private void campoEnderecoALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEnderecoALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEnderecoALActionPerformed

    private void campoCEPALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCEPALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCEPALActionPerformed

    private void campoRGALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRGALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRGALActionPerformed

    private void campoCPFALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCPFALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCPFALActionPerformed

    private void campoNomeALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeALActionPerformed

    private void campoDataNascALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataNascALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataNascALActionPerformed

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JTelaEditarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JTelaEditarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JTelaEditarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JTelaEditarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTelaEditarAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JTextField campoCEPAL;
    private javax.swing.JTextField campoCPFAL;
    private javax.swing.JTextField campoDataNascAL;
    private javax.swing.JTextField campoEmailAL;
    private javax.swing.JTextField campoEnderecoAL;
    private javax.swing.JTextField campoNomeAL;
    private javax.swing.JTextField campoRGAL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JLabel labelCEPAL;
    private javax.swing.JLabel labelCPFAL;
    private javax.swing.JLabel labelConfirmacaoSenhaAL;
    private javax.swing.JLabel labelDataNascAL;
    private javax.swing.JLabel labelEditAluno;
    private javax.swing.JLabel labelEmailAL;
    private javax.swing.JLabel labelEnderecoAL;
    private javax.swing.JLabel labelNomeAL;
    private javax.swing.JLabel labelRGAL;
    private javax.swing.JLabel labelSenhaAL;
    // End of variables declaration//GEN-END:variables
}
