package View;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Usuario
 */
public class JTelaVisualizarAluno extends javax.swing.JFrame {

    /**
     * Creates new form TelaVisualizarAluno
     */
    public JTelaVisualizarAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCentro4 = new javax.swing.JPanel();
        labelVisualizarSecretario4 = new javax.swing.JLabel();
        buttonVoltar4 = new javax.swing.JButton();
        labelDataNasc = new javax.swing.JLabel();
        labelRG = new javax.swing.JLabel();
        labelEndereco = new javax.swing.JLabel();
        labelContrato = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelCEP = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelCampoNome = new javax.swing.JLabel();
        labelCampoDataNasc = new javax.swing.JLabel();
        labelCampoRG = new javax.swing.JLabel();
        labelCampoEndereco = new javax.swing.JLabel();
        labelCampoCEP = new javax.swing.JLabel();
        labelCampoEmail = new javax.swing.JLabel();
        labelCampoContrato = new javax.swing.JLabel();
        labelCampoCPF = new javax.swing.JLabel();
        labelCPF = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelTopo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelLateral = new javax.swing.JPanel();
        labelSecretarios = new javax.swing.JLabel();
        labelPersonalTrainers = new javax.swing.JLabel();
        labelEquipamentos = new javax.swing.JLabel();
        labelAlunos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCentro4.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCentro4.setLayout(null);

        labelVisualizarSecretario4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelVisualizarSecretario4.setText("Visualizar Aluno");
        jPanelCentro4.add(labelVisualizarSecretario4);
        labelVisualizarSecretario4.setBounds(30, 20, 260, 40);

        buttonVoltar4.setBackground(new java.awt.Color(0, 255, 0));
        buttonVoltar4.setText("Voltar");
        buttonVoltar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltar4ActionPerformed(evt);
            }
        });
        jPanelCentro4.add(buttonVoltar4);
        buttonVoltar4.setBounds(410, 500, 130, 23);

        labelDataNasc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelDataNasc.setText("Data de nascimento:");
        jPanelCentro4.add(labelDataNasc);
        labelDataNasc.setBounds(30, 300, 200, 30);

        labelRG.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelRG.setText("RG:");
        jPanelCentro4.add(labelRG);
        labelRG.setBounds(30, 330, 40, 30);

        labelEndereco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelEndereco.setText("Endereço:");
        jPanelCentro4.add(labelEndereco);
        labelEndereco.setBounds(30, 360, 100, 30);

        labelContrato.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelContrato.setText("Matrícula:");
        jPanelCentro4.add(labelContrato);
        labelContrato.setBounds(30, 450, 150, 30);

        labelEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelEmail.setText("Email:");
        jPanelCentro4.add(labelEmail);
        labelEmail.setBounds(30, 420, 70, 30);

        labelCEP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelCEP.setText("CEP:");
        jPanelCentro4.add(labelCEP);
        labelCEP.setBounds(30, 390, 50, 30);

        labelNome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelNome.setText("Nome:");
        jPanelCentro4.add(labelNome);
        labelNome.setBounds(30, 270, 70, 30);

        labelCampoNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCampoNome.setText("Jaime Valverde");
        jPanelCentro4.add(labelCampoNome);
        labelCampoNome.setBounds(100, 270, 210, 30);

        labelCampoDataNasc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCampoDataNasc.setText("25/12/1996");
        jPanelCentro4.add(labelCampoDataNasc);
        labelCampoDataNasc.setBounds(220, 300, 210, 30);

        labelCampoRG.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCampoRG.setText("000.000.000-00");
        jPanelCentro4.add(labelCampoRG);
        labelCampoRG.setBounds(70, 330, 180, 30);

        labelCampoEndereco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCampoEndereco.setText("Rua Profª Virginia 119");
        jPanelCentro4.add(labelCampoEndereco);
        labelCampoEndereco.setBounds(130, 360, 210, 30);

        labelCampoCEP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCampoCEP.setText("45208209");
        jPanelCentro4.add(labelCampoCEP);
        labelCampoCEP.setBounds(80, 390, 210, 30);

        labelCampoEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCampoEmail.setText("jaimevalverde.jv@gmail.com");
        jPanelCentro4.add(labelCampoEmail);
        labelCampoEmail.setBounds(90, 420, 240, 30);

        labelCampoContrato.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCampoContrato.setText("20171512");
        jPanelCentro4.add(labelCampoContrato);
        labelCampoContrato.setBounds(180, 450, 210, 30);

        labelCampoCPF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCampoCPF.setText("000.000.000.00");
        jPanelCentro4.add(labelCampoCPF);
        labelCampoCPF.setBounds(300, 330, 210, 30);

        labelCPF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelCPF.setText("CPF:");
        jPanelCentro4.add(labelCPF);
        labelCPF.setBounds(250, 330, 50, 30);

        jLabel5.setText("FOTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel5)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel5)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jPanelCentro4.add(jPanel1);
        jPanel1.setBounds(190, 80, 150, 170);

        jPanelTopo.setBackground(new java.awt.Color(0, 255, 0));
        jPanelTopo.setPreferredSize(new java.awt.Dimension(694, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SoFiT");

        javax.swing.GroupLayout jPanelTopoLayout = new javax.swing.GroupLayout(jPanelTopo);
        jPanelTopo.setLayout(jPanelTopoLayout);
        jPanelTopoLayout.setHorizontalGroup(
            jPanelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(738, Short.MAX_VALUE))
        );
        jPanelTopoLayout.setVerticalGroup(
            jPanelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopoLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jPanelLateral.setBackground(new java.awt.Color(103, 152, 104));
        jPanelLateral.setPreferredSize(new java.awt.Dimension(200, 570));

        labelSecretarios.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        labelSecretarios.setForeground(new java.awt.Color(255, 255, 255));
        labelSecretarios.setText("Secretários");

        labelPersonalTrainers.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        labelPersonalTrainers.setForeground(new java.awt.Color(255, 255, 255));
        labelPersonalTrainers.setText("Personal Trainers");

        labelEquipamentos.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        labelEquipamentos.setForeground(new java.awt.Color(255, 255, 255));
        labelEquipamentos.setText("Equipamentos");

        labelAlunos.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        labelAlunos.setForeground(new java.awt.Color(255, 255, 255));
        labelAlunos.setText("Alunos");

        javax.swing.GroupLayout jPanelLateralLayout = new javax.swing.GroupLayout(jPanelLateral);
        jPanelLateral.setLayout(jPanelLateralLayout);
        jPanelLateralLayout.setHorizontalGroup(
            jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPersonalTrainers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addGroup(jPanelLateralLayout.createSequentialGroup()
                        .addGroup(jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSecretarios, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEquipamentos))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelLateralLayout.setVerticalGroup(
            jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateralLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(labelAlunos)
                .addGap(18, 18, 18)
                .addComponent(labelSecretarios)
                .addGap(18, 18, 18)
                .addComponent(labelPersonalTrainers)
                .addGap(18, 18, 18)
                .addComponent(labelEquipamentos)
                .addContainerGap(382, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelTopo, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jPanelCentro4, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelCentro4, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonVoltar4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JTelaVisualizarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JTelaVisualizarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JTelaVisualizarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JTelaVisualizarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTelaVisualizarAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonVoltar4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCentro4;
    private javax.swing.JPanel jPanelLateral;
    private javax.swing.JPanel jPanelTopo;
    private javax.swing.JLabel labelAlunos;
    private javax.swing.JLabel labelCEP;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelCampoCEP;
    private javax.swing.JLabel labelCampoCPF;
    private javax.swing.JLabel labelCampoContrato;
    private javax.swing.JLabel labelCampoDataNasc;
    private javax.swing.JLabel labelCampoEmail;
    private javax.swing.JLabel labelCampoEndereco;
    private javax.swing.JLabel labelCampoNome;
    private javax.swing.JLabel labelCampoRG;
    private javax.swing.JLabel labelContrato;
    private javax.swing.JLabel labelDataNasc;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelEquipamentos;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPersonalTrainers;
    private javax.swing.JLabel labelRG;
    private javax.swing.JLabel labelSecretarios;
    private javax.swing.JLabel labelVisualizarSecretario4;
    // End of variables declaration//GEN-END:variables
}
