package View;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Usuario
 */
public class JTelaCadastrarPersonal extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastrarPersonal
     */
    public JTelaCadastrarPersonal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTopo2 = new javax.swing.JPanel();
        labelSenha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        buttonCancelarTreino = new javax.swing.JButton();
        buttonSalvarTreino = new javax.swing.JButton();
        labelUsuario2 = new javax.swing.JLabel();
        campoUsuario3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jSpinner3 = new javax.swing.JSpinner();
        panelBg = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelTopo2.setBackground(new java.awt.Color(255, 255, 255));
        panelTopo2.setLayout(null);

        labelSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSenha.setText("Início de Contrato:");
        panelTopo2.add(labelSenha);
        labelSenha.setBounds(460, 180, 140, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Cadastrar Personal");
        panelTopo2.add(jLabel1);
        jLabel1.setBounds(130, 40, 210, 25);

        buttonCancelarTreino.setBackground(new java.awt.Color(255, 0, 0));
        buttonCancelarTreino.setText("Cancelar");
        buttonCancelarTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarTreinoActionPerformed(evt);
            }
        });
        panelTopo2.add(buttonCancelarTreino);
        buttonCancelarTreino.setBounds(450, 510, 133, 23);

        buttonSalvarTreino.setBackground(new java.awt.Color(0, 255, 0));
        buttonSalvarTreino.setText("Salvar");
        buttonSalvarTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarTreinoActionPerformed(evt);
            }
        });
        panelTopo2.add(buttonSalvarTreino);
        buttonSalvarTreino.setBounds(590, 510, 133, 23);

        labelUsuario2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelUsuario2.setText("Nome:");
        panelTopo2.add(labelUsuario2);
        labelUsuario2.setBounds(460, 70, 52, 17);

        campoUsuario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuario3ActionPerformed(evt);
            }
        });
        panelTopo2.add(campoUsuario3);
        campoUsuario3.setBounds(460, 90, 230, 33);

        jLabel9.setText("Dia:");
        panelTopo2.add(jLabel9);
        jLabel9.setBounds(480, 210, 30, 20);

        jLabel10.setText("Mês:");
        panelTopo2.add(jLabel10);
        jLabel10.setBounds(550, 210, 40, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Feveireiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        panelTopo2.add(jComboBox3);
        jComboBox3.setBounds(540, 240, 80, 20);

        jLabel11.setText("Ano:");
        panelTopo2.add(jLabel11);
        jLabel11.setBounds(660, 200, 30, 20);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        panelTopo2.add(jComboBox5);
        jComboBox5.setBounds(470, 240, 40, 20);

        jLabel5.setText("FOTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel5)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel5)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        panelTopo2.add(jPanel1);
        jPanel1.setBounds(140, 110, 150, 170);

        jButton1.setText("Browser");
        panelTopo2.add(jButton1);
        jButton1.setBounds(260, 300, 71, 23);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        panelTopo2.add(jTextField3);
        jTextField3.setBounds(140, 300, 110, 20);

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(1900, null, 2016, 1));
        jSpinner3.setValue(2016);
        panelTopo2.add(jSpinner3);
        jSpinner3.setBounds(650, 230, 70, 30);

        panelBg.setBackground(new java.awt.Color(0, 255, 0));
        panelBg.setPreferredSize(new java.awt.Dimension(694, 30));

        labelLogo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelLogo.setForeground(new java.awt.Color(255, 255, 255));
        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setText("SoFiT");

        javax.swing.GroupLayout panelBgLayout = new javax.swing.GroupLayout(panelBg);
        panelBg.setLayout(panelBgLayout);
        panelBgLayout.setHorizontalGroup(
            panelBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo)
                .addContainerGap(738, Short.MAX_VALUE))
        );
        panelBgLayout.setVerticalGroup(
            panelBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBgLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(labelLogo))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBg, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelTopo2, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelBg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(panelTopo2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelarTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarTreinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelarTreinoActionPerformed

    private void buttonSalvarTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarTreinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSalvarTreinoActionPerformed

    private void campoUsuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuario3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JTelaCadastrarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JTelaCadastrarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JTelaCadastrarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JTelaCadastrarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTelaCadastrarPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelarTreino;
    private javax.swing.JButton buttonSalvarTreino;
    private javax.swing.JTextField campoUsuario3;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelUsuario2;
    private javax.swing.JPanel panelBg;
    private javax.swing.JPanel panelTopo2;
    // End of variables declaration//GEN-END:variables
}
