package View;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Usuario
 */
public class JTelaManutençãoDeEqpmt extends javax.swing.JFrame {

    /**
     * Creates new form TelaManutençãoDeEqmt
     */
    public JTelaManutençãoDeEqpmt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBg = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        panelTopo2 = new javax.swing.JPanel();
        labelSenha = new javax.swing.JLabel();
        LabelEquipamento = new javax.swing.JLabel();
        buttonSalvarTreino = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelUsuario2 = new javax.swing.JLabel();
        campoUsuario3 = new javax.swing.JTextField();
        labelSenha1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        labelSenha2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBg.setBackground(new java.awt.Color(0, 255, 0));
        panelBg.setPreferredSize(new java.awt.Dimension(694, 30));

        labelLogo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelLogo.setForeground(new java.awt.Color(255, 255, 255));
        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setText("SoFiT");

        javax.swing.GroupLayout panelBgLayout = new javax.swing.GroupLayout(panelBg);
        panelBg.setLayout(panelBgLayout);
        panelBgLayout.setHorizontalGroup(
            panelBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo)
                .addContainerGap(738, Short.MAX_VALUE))
        );
        panelBgLayout.setVerticalGroup(
            panelBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBgLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(labelLogo))
        );

        panelTopo2.setBackground(new java.awt.Color(255, 255, 255));
        panelTopo2.setLayout(null);

        labelSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSenha.setText("Data de aquisição:");
        panelTopo2.add(labelSenha);
        labelSenha.setBounds(310, 150, 130, 20);

        LabelEquipamento.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        LabelEquipamento.setText("Manutenção de Equipamento");
        panelTopo2.add(LabelEquipamento);
        LabelEquipamento.setBounds(30, 20, 300, 25);

        buttonSalvarTreino.setBackground(new java.awt.Color(0, 255, 0));
        buttonSalvarTreino.setText("Enviar");
        buttonSalvarTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarTreinoActionPerformed(evt);
            }
        });
        panelTopo2.add(buttonSalvarTreino);
        buttonSalvarTreino.setBounds(620, 530, 133, 23);

        jLabel2.setText("Mês:");
        panelTopo2.add(jLabel2);
        jLabel2.setBounds(140, 470, 40, 20);

        jLabel3.setText("Ano:");
        panelTopo2.add(jLabel3);
        jLabel3.setBounds(270, 470, 30, 20);

        jLabel4.setText("Dia:");
        panelTopo2.add(jLabel4);
        jLabel4.setBounds(60, 470, 30, 20);

        labelUsuario2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelUsuario2.setText("Nome:");
        panelTopo2.add(labelUsuario2);
        labelUsuario2.setBounds(310, 70, 52, 17);

        campoUsuario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuario3ActionPerformed(evt);
            }
        });
        panelTopo2.add(campoUsuario3);
        campoUsuario3.setBounds(310, 90, 230, 33);

        labelSenha1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSenha1.setText("Saída:");
        panelTopo2.add(labelSenha1);
        labelSenha1.setBounds(20, 440, 130, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Feveireiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        panelTopo2.add(jComboBox2);
        jComboBox2.setBounds(140, 500, 80, 20);

        jLabel9.setText("Dia:");
        panelTopo2.add(jLabel9);
        jLabel9.setBounds(310, 190, 30, 20);

        jLabel10.setText("Mês:");
        panelTopo2.add(jLabel10);
        jLabel10.setBounds(380, 190, 40, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Feveireiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        panelTopo2.add(jComboBox3);
        jComboBox3.setBounds(370, 220, 80, 20);

        jLabel11.setText("Ano:");
        panelTopo2.add(jLabel11);
        jLabel11.setBounds(490, 190, 30, 20);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        panelTopo2.add(jComboBox5);
        jComboBox5.setBounds(300, 220, 40, 20);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        panelTopo2.add(jComboBox6);
        jComboBox6.setBounds(50, 500, 40, 20);

        jLabel5.setText("FOTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel5)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel5)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        panelTopo2.add(jPanel1);
        jPanel1.setBounds(50, 120, 150, 170);

        labelSenha2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSenha2.setText("Retorno:");
        panelTopo2.add(labelSenha2);
        labelSenha2.setBounds(20, 330, 130, 20);

        jLabel12.setText("Dia:");
        panelTopo2.add(jLabel12);
        jLabel12.setBounds(60, 360, 30, 20);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        panelTopo2.add(jComboBox7);
        jComboBox7.setBounds(60, 390, 40, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Feveireiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        panelTopo2.add(jComboBox4);
        jComboBox4.setBounds(140, 390, 80, 20);

        jLabel13.setText("Mês:");
        panelTopo2.add(jLabel13);
        jLabel13.setBounds(150, 360, 40, 20);

        jLabel14.setText("Ano:");
        panelTopo2.add(jLabel14);
        jLabel14.setBounds(250, 360, 30, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        panelTopo2.add(jScrollPane1);
        jScrollPane1.setBounds(430, 380, 240, 96);

        jLabel1.setText("Observações:");
        panelTopo2.add(jLabel1);
        jLabel1.setBounds(430, 350, 90, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aeróbico", "Funcional", "Hipertrofia" }));
        panelTopo2.add(jComboBox1);
        jComboBox1.setBounds(600, 100, 90, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Tipo:");
        panelTopo2.add(jLabel6);
        jLabel6.setBounds(600, 70, 40, 16);

        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(1900, null, 2016, 1));
        jSpinner4.setValue(2016);
        panelTopo2.add(jSpinner4);
        jSpinner4.setBounds(480, 220, 70, 30);

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(1900, null, 2016, 1));
        jSpinner3.setValue(2016);
        panelTopo2.add(jSpinner3);
        jSpinner3.setBounds(250, 390, 70, 30);

        jSpinner5.setModel(new javax.swing.SpinnerNumberModel(1900, null, 2016, 1));
        jSpinner5.setValue(2016);
        panelTopo2.add(jSpinner5);
        jSpinner5.setBounds(260, 500, 70, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBg, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelTopo2, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelBg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(panelTopo2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSalvarTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarTreinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSalvarTreinoActionPerformed

    private void campoUsuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuario3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JTelaManutençãoDeEqpmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JTelaManutençãoDeEqpmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JTelaManutençãoDeEqpmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JTelaManutençãoDeEqpmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTelaManutençãoDeEqpmt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelEquipamento;
    private javax.swing.JButton buttonSalvarTreino;
    private javax.swing.JTextField campoUsuario3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelSenha1;
    private javax.swing.JLabel labelSenha2;
    private javax.swing.JLabel labelUsuario2;
    private javax.swing.JPanel panelBg;
    private javax.swing.JPanel panelTopo2;
    // End of variables declaration//GEN-END:variables
}
