/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author iMurilo Cruz
 */
public class TelaGestaoSecretario extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaGestaoSecretario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCentro = new javax.swing.JPanel();
        campoPesquisar = new javax.swing.JTextField();
        labelGestaoSecretario = new javax.swing.JLabel();
        buttonCadastrar = new javax.swing.JButton();
        labelPesquisar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResultadoPesquisa = new javax.swing.JTable();
        jPanelTopo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelLateral = new javax.swing.JPanel();
        labelSecretarios = new javax.swing.JLabel();
        labelPersonalTrainers = new javax.swing.JLabel();
        labelEquipamentos = new javax.swing.JLabel();
        labelAlunos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanelCentro.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCentro.setLayout(null);

        campoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPesquisarActionPerformed(evt);
            }
        });
        jPanelCentro.add(campoPesquisar);
        campoPesquisar.setBounds(380, 120, 170, 33);

        labelGestaoSecretario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelGestaoSecretario.setText("Gestão de Secretário");
        jPanelCentro.add(labelGestaoSecretario);
        labelGestaoSecretario.setBounds(30, 20, 260, 40);

        buttonCadastrar.setText("Cadastrar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });
        jPanelCentro.add(buttonCadastrar);
        buttonCadastrar.setBounds(420, 90, 130, 23);

        labelPesquisar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelPesquisar.setText("Pesquisar: ");
        jPanelCentro.add(labelPesquisar);
        labelPesquisar.setBounds(270, 120, 100, 30);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTableResultadoPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nº", "Nome", "Nº de Contrato", "Ações"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableResultadoPesquisa);
        if (jTableResultadoPesquisa.getColumnModel().getColumnCount() > 0) {
            jTableResultadoPesquisa.getColumnModel().getColumn(0).setResizable(false);
            jTableResultadoPesquisa.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTableResultadoPesquisa.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTableResultadoPesquisa.getColumnModel().getColumn(2).setPreferredWidth(60);
            jTableResultadoPesquisa.getColumnModel().getColumn(3).setPreferredWidth(80);
        }

        jPanelCentro.add(jScrollPane1);
        jScrollPane1.setBounds(50, 160, 500, 190);

        getContentPane().add(jPanelCentro, java.awt.BorderLayout.CENTER);

        jPanelTopo.setBackground(new java.awt.Color(0, 255, 0));
        jPanelTopo.setPreferredSize(new java.awt.Dimension(694, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SoFiT");

        javax.swing.GroupLayout jPanelTopoLayout = new javax.swing.GroupLayout(jPanelTopo);
        jPanelTopo.setLayout(jPanelTopoLayout);
        jPanelTopoLayout.setHorizontalGroup(
            jPanelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(738, Short.MAX_VALUE))
        );
        jPanelTopoLayout.setVerticalGroup(
            jPanelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopoLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        getContentPane().add(jPanelTopo, java.awt.BorderLayout.PAGE_START);

        jPanelLateral.setBackground(new java.awt.Color(103, 152, 104));
        jPanelLateral.setPreferredSize(new java.awt.Dimension(200, 570));

        labelSecretarios.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        labelSecretarios.setForeground(new java.awt.Color(255, 255, 255));
        labelSecretarios.setText("Secretários");

        labelPersonalTrainers.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        labelPersonalTrainers.setForeground(new java.awt.Color(255, 255, 255));
        labelPersonalTrainers.setText("Personal Trainers");

        labelEquipamentos.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        labelEquipamentos.setForeground(new java.awt.Color(255, 255, 255));
        labelEquipamentos.setText("Equipamentos");

        labelAlunos.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        labelAlunos.setForeground(new java.awt.Color(255, 255, 255));
        labelAlunos.setText("Alunos");

        javax.swing.GroupLayout jPanelLateralLayout = new javax.swing.GroupLayout(jPanelLateral);
        jPanelLateral.setLayout(jPanelLateralLayout);
        jPanelLateralLayout.setHorizontalGroup(
            jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPersonalTrainers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addGroup(jPanelLateralLayout.createSequentialGroup()
                        .addGroup(jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSecretarios, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEquipamentos))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelLateralLayout.setVerticalGroup(
            jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateralLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(labelAlunos)
                .addGap(18, 18, 18)
                .addComponent(labelSecretarios)
                .addGap(18, 18, 18)
                .addComponent(labelPersonalTrainers)
                .addGap(18, 18, 18)
                .addComponent(labelEquipamentos)
                .addContainerGap(382, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelLateral, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPesquisarActionPerformed

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGestaoSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGestaoSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGestaoSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGestaoSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGestaoSecretario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JTextField campoPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelCentro;
    private javax.swing.JPanel jPanelLateral;
    private javax.swing.JPanel jPanelTopo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableResultadoPesquisa;
    private javax.swing.JLabel labelAlunos;
    private javax.swing.JLabel labelEquipamentos;
    private javax.swing.JLabel labelGestaoSecretario;
    private javax.swing.JLabel labelPersonalTrainers;
    private javax.swing.JLabel labelPesquisar;
    private javax.swing.JLabel labelSecretarios;
    // End of variables declaration//GEN-END:variables
}
