/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author iMurilo Cruz
 */
public class TelaEditarSecretario extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaEditarSecretario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        campoUsuario = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        labelSenha = new javax.swing.JLabel();
        buttonLogar = new javax.swing.JButton();
        labelUsuario = new javax.swing.JLabel();
        campoUsuario1 = new javax.swing.JTextField();
        labelUsuario1 = new javax.swing.JLabel();
        campoUsuario2 = new javax.swing.JTextField();
        labelUsuario2 = new javax.swing.JLabel();
        labelSenha1 = new javax.swing.JLabel();
        campoSenha1 = new javax.swing.JPasswordField();
        campoUsuario3 = new javax.swing.JTextField();
        labelUsuario3 = new javax.swing.JLabel();
        labelUsuario4 = new javax.swing.JLabel();
        campoUsuario4 = new javax.swing.JTextField();
        labelUsuario5 = new javax.swing.JLabel();
        campoUsuario5 = new javax.swing.JTextField();
        labelUsuario6 = new javax.swing.JLabel();
        campoUsuario6 = new javax.swing.JTextField();
        campoUsuario7 = new javax.swing.JTextField();
        labelUsuario7 = new javax.swing.JLabel();
        labelUsuario8 = new javax.swing.JLabel();
        campoUsuario8 = new javax.swing.JTextField();
        campoUsuario9 = new javax.swing.JTextField();
        labelUsuario9 = new javax.swing.JLabel();
        buttonLogar1 = new javax.swing.JButton();
        labelUsuario10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        campoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(campoUsuario);
        campoUsuario.setBounds(170, 340, 200, 33);

        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(campoSenha);
        campoSenha.setBounds(170, 410, 200, 31);

        labelSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSenha.setText("Senha");
        jPanel1.add(labelSenha);
        labelSenha.setBounds(170, 390, 43, 17);

        buttonLogar.setText("Cancelar");
        buttonLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonLogar);
        buttonLogar.setBounds(440, 470, 133, 23);

        labelUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelUsuario.setText("Inicio de contrato:");
        jPanel1.add(labelUsuario);
        labelUsuario.setBounds(170, 320, 140, 17);

        campoUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuario1ActionPerformed(evt);
            }
        });
        jPanel1.add(campoUsuario1);
        campoUsuario1.setBounds(400, 340, 200, 33);

        labelUsuario1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelUsuario1.setText("Termino de contrato:");
        jPanel1.add(labelUsuario1);
        labelUsuario1.setBounds(400, 320, 150, 17);

        campoUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuario2ActionPerformed(evt);
            }
        });
        jPanel1.add(campoUsuario2);
        campoUsuario2.setBounds(170, 280, 250, 33);

        labelUsuario2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelUsuario2.setText("Email:");
        jPanel1.add(labelUsuario2);
        labelUsuario2.setBounds(170, 260, 41, 17);

        labelSenha1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSenha1.setText("Confirmação de Senha:");
        jPanel1.add(labelSenha1);
        labelSenha1.setBounds(400, 390, 170, 17);

        campoSenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenha1ActionPerformed(evt);
            }
        });
        jPanel1.add(campoSenha1);
        campoSenha1.setBounds(400, 410, 200, 31);

        campoUsuario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuario3ActionPerformed(evt);
            }
        });
        jPanel1.add(campoUsuario3);
        campoUsuario3.setBounds(440, 280, 160, 33);

        labelUsuario3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelUsuario3.setText("Nº de contrato:");
        jPanel1.add(labelUsuario3);
        labelUsuario3.setBounds(440, 260, 120, 17);

        labelUsuario4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelUsuario4.setText("Endereço:");
        jPanel1.add(labelUsuario4);
        labelUsuario4.setBounds(170, 200, 90, 17);

        campoUsuario4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuario4ActionPerformed(evt);
            }
        });
        jPanel1.add(campoUsuario4);
        campoUsuario4.setBounds(170, 220, 290, 33);

        labelUsuario5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelUsuario5.setText("CEP:");
        jPanel1.add(labelUsuario5);
        labelUsuario5.setBounds(480, 200, 120, 17);

        campoUsuario5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuario5ActionPerformed(evt);
            }
        });
        jPanel1.add(campoUsuario5);
        campoUsuario5.setBounds(480, 220, 120, 33);

        labelUsuario6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelUsuario6.setText("RG:");
        jPanel1.add(labelUsuario6);
        labelUsuario6.setBounds(170, 140, 140, 17);

        campoUsuario6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuario6ActionPerformed(evt);
            }
        });
        jPanel1.add(campoUsuario6);
        campoUsuario6.setBounds(170, 160, 200, 33);

        campoUsuario7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuario7ActionPerformed(evt);
            }
        });
        jPanel1.add(campoUsuario7);
        campoUsuario7.setBounds(400, 160, 200, 33);

        labelUsuario7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelUsuario7.setText("CPF:");
        jPanel1.add(labelUsuario7);
        labelUsuario7.setBounds(400, 140, 150, 17);

        labelUsuario8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelUsuario8.setText("Nome:");
        jPanel1.add(labelUsuario8);
        labelUsuario8.setBounds(170, 80, 140, 17);

        campoUsuario8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuario8ActionPerformed(evt);
            }
        });
        jPanel1.add(campoUsuario8);
        campoUsuario8.setBounds(170, 100, 200, 33);

        campoUsuario9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuario9ActionPerformed(evt);
            }
        });
        jPanel1.add(campoUsuario9);
        campoUsuario9.setBounds(400, 100, 200, 33);

        labelUsuario9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelUsuario9.setText("Editar Secretário");
        jPanel1.add(labelUsuario9);
        labelUsuario9.setBounds(120, 20, 220, 40);

        buttonLogar1.setText("Salvar");
        buttonLogar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogar1ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonLogar1);
        buttonLogar1.setBounds(580, 470, 133, 23);

        labelUsuario10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelUsuario10.setText("Data de nascimento:");
        jPanel1.add(labelUsuario10);
        labelUsuario10.setBounds(400, 80, 150, 17);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(0, 255, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(694, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SoFiT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(738, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuarioActionPerformed

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaActionPerformed

    private void buttonLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLogarActionPerformed

    private void campoUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuario1ActionPerformed

    private void campoUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuario2ActionPerformed

    private void campoSenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenha1ActionPerformed

    private void campoUsuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuario3ActionPerformed

    private void campoUsuario4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuario4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuario4ActionPerformed

    private void campoUsuario5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuario5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuario5ActionPerformed

    private void campoUsuario6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuario6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuario6ActionPerformed

    private void campoUsuario7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuario7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuario7ActionPerformed

    private void campoUsuario8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuario8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuario8ActionPerformed

    private void campoUsuario9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuario9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuario9ActionPerformed

    private void buttonLogar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLogar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditarSecretario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogar;
    private javax.swing.JButton buttonLogar1;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JPasswordField campoSenha1;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JTextField campoUsuario1;
    private javax.swing.JTextField campoUsuario2;
    private javax.swing.JTextField campoUsuario3;
    private javax.swing.JTextField campoUsuario4;
    private javax.swing.JTextField campoUsuario5;
    private javax.swing.JTextField campoUsuario6;
    private javax.swing.JTextField campoUsuario7;
    private javax.swing.JTextField campoUsuario8;
    private javax.swing.JTextField campoUsuario9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelSenha1;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel labelUsuario1;
    private javax.swing.JLabel labelUsuario10;
    private javax.swing.JLabel labelUsuario2;
    private javax.swing.JLabel labelUsuario3;
    private javax.swing.JLabel labelUsuario4;
    private javax.swing.JLabel labelUsuario5;
    private javax.swing.JLabel labelUsuario6;
    private javax.swing.JLabel labelUsuario7;
    private javax.swing.JLabel labelUsuario8;
    private javax.swing.JLabel labelUsuario9;
    // End of variables declaration//GEN-END:variables
}
